// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8q_KMougkpGbJcjVCOxLzFF9-6H7wQQ',
    appId: '1:614233415801:web:82e18fef6ea6b706bfb4a8',
    messagingSenderId: '614233415801',
    projectId: 'pokedexflutter-05',
    authDomain: 'pokedexflutter-05.firebaseapp.com',
    storageBucket: 'pokedexflutter-05.firebasestorage.app',
    measurementId: 'G-VNFW4GEVMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAFCjr4fXZ6uVcxfHb03bAx-oX0W1dSw',
    appId: '1:614233415801:android:9b55a120cde6515cbfb4a8',
    messagingSenderId: '614233415801',
    projectId: 'pokedexflutter-05',
    storageBucket: 'pokedexflutter-05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGvStKhrGo01MAJI3jcCAWP7PC0hmJBs',
    appId: '1:614233415801:ios:12fb19f00a8cd1e8bfb4a8',
    messagingSenderId: '614233415801',
    projectId: 'pokedexflutter-05',
    storageBucket: 'pokedexflutter-05.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGvStKhrGo01MAJI3jcCAWP7PC0hmJBs',
    appId: '1:614233415801:ios:12fb19f00a8cd1e8bfb4a8',
    messagingSenderId: '614233415801',
    projectId: 'pokedexflutter-05',
    storageBucket: 'pokedexflutter-05.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC8q_KMougkpGbJcjVCOxLzFF9-6H7wQQ',
    appId: '1:614233415801:web:b07c568bb3b15d3ebfb4a8',
    messagingSenderId: '614233415801',
    projectId: 'pokedexflutter-05',
    authDomain: 'pokedexflutter-05.firebaseapp.com',
    storageBucket: 'pokedexflutter-05.firebasestorage.app',
    measurementId: 'G-3RH5KE3109',
  );
}
